[package]
name = "qhist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
statistical = "1.0.0"
hdrhistogram = "7.5.0"
clap = "3.2.8"
pad = "0.1.6"